"""
registry.py — AUTO-GENERATED by config/generate.py
DO NOT EDIT MANUALLY. Edit config/workflow_config.json and re-run generate.py.
"""

from __future__ import annotations

import os
from typing import Any


STEP_CONFIG: dict[str, dict[str, Any]] = {
        "STEP_00": {
                "name": "Intake & Normalization",
                "description": "Parse the conditions, the submitted documents (rack & stack output), the loan scenario (MISMO XML), and the eligibility output. Normalize categories and build an evaluation scenario summary.",
                "plan_file": "step_00_intake.md",
                "tools": [
                        "parse_conditions",
                        "parse_documents",
                        "build_eval_scenario"
                ],
                "substeps": [
                        {
                                "id": "0.1",
                                "name": "Parse conditions list",
                                "tools": [
                                        "parse_conditions"
                                ]
                        },
                        {
                                "id": "0.2",
                                "name": "Parse submitted documents (R&S output)",
                                "tools": [
                                        "parse_documents"
                                ]
                        },
                        {
                                "id": "0.3",
                                "name": "Build evaluation scenario summary",
                                "tools": [
                                        "build_eval_scenario"
                                ]
                        },
                        {
                                "id": "0.4",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        },
        "STEP_01": {
                "name": "Candidate Matching (Relevance Check)",
                "description": "Link conditions to the documents that may satisfy them. Pre-links from each condition's result_document_ids are authoritative; a deterministic keyword pass, an OCR relevance check (first pages, escalate to full), and LLM triage supplement them.",
                "plan_file": "step_01_candidate_matching.md",
                "tools": [
                        "deterministic_candidate_match",
                        "get_document_ocr",
                        "store_candidate_matches"
                ],
                "substeps": [
                        {
                                "id": "1.1",
                                "name": "Deterministic candidate match (result_document_ids + keywords)",
                                "tools": [
                                        "deterministic_candidate_match"
                                ]
                        },
                        {
                                "id": "1.2",
                                "name": "OCR relevance check (first pages, escalate to full)",
                                "tools": [
                                        "get_document_ocr"
                                ]
                        },
                        {
                                "id": "1.3",
                                "name": "Store final candidate map",
                                "tools": [
                                        "store_candidate_matches"
                                ]
                        },
                        {
                                "id": "1.4",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        },
        "STEP_02": {
                "name": "Income Condition Evaluation",
                "description": "Deep fulfillment evaluation for income-category conditions against their candidate documents.",
                "plan_file": "step_02_income.md",
                "tools": [
                        "get_conditions_to_evaluate",
                        "get_document_ocr",
                        "load_guideline_sections",
                        "store_income_evaluations"
                ],
                "substeps": [
                        {
                                "id": "2.1",
                                "name": "Load income conditions + candidate documents",
                                "tools": [
                                        "get_conditions_to_evaluate"
                                ]
                        },
                        {
                                "id": "2.2",
                                "name": "Load income guideline sections (if needed)",
                                "tools": [
                                        "load_guideline_sections"
                                ]
                        },
                        {
                                "id": "2.3",
                                "name": "Store income evaluations",
                                "tools": [
                                        "store_income_evaluations"
                                ]
                        },
                        {
                                "id": "2.4",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        },
        "STEP_03": {
                "name": "Assets & Reserves Condition Evaluation",
                "description": "Deep fulfillment evaluation for asset/reserves-category conditions against their candidate documents.",
                "plan_file": "step_03_assets.md",
                "tools": [
                        "get_conditions_to_evaluate",
                        "get_document_ocr",
                        "load_guideline_sections",
                        "store_assets_evaluations"
                ],
                "substeps": [
                        {
                                "id": "3.1",
                                "name": "Load asset conditions + candidate documents",
                                "tools": [
                                        "get_conditions_to_evaluate"
                                ]
                        },
                        {
                                "id": "3.2",
                                "name": "Load asset/reserves guideline sections (if needed)",
                                "tools": [
                                        "load_guideline_sections"
                                ]
                        },
                        {
                                "id": "3.3",
                                "name": "Store asset evaluations",
                                "tools": [
                                        "store_assets_evaluations"
                                ]
                        },
                        {
                                "id": "3.4",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        },
        "STEP_04": {
                "name": "Credit Condition Evaluation",
                "description": "Deep fulfillment evaluation for credit-category conditions (including identity, housing history, undisclosed property) against their candidate documents.",
                "plan_file": "step_04_credit.md",
                "tools": [
                        "get_conditions_to_evaluate",
                        "get_document_ocr",
                        "load_guideline_sections",
                        "store_credit_evaluations"
                ],
                "substeps": [
                        {
                                "id": "4.1",
                                "name": "Load credit conditions + candidate documents",
                                "tools": [
                                        "get_conditions_to_evaluate"
                                ]
                        },
                        {
                                "id": "4.2",
                                "name": "Load credit guideline sections (if needed)",
                                "tools": [
                                        "load_guideline_sections"
                                ]
                        },
                        {
                                "id": "4.3",
                                "name": "Store credit evaluations",
                                "tools": [
                                        "store_credit_evaluations"
                                ]
                        },
                        {
                                "id": "4.4",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        },
        "STEP_05": {
                "name": "Property Condition Evaluation",
                "description": "Deep fulfillment evaluation for property-category conditions (appraisal, title, insurance, taxes, purchase agreement, flood) against their candidate documents.",
                "plan_file": "step_05_property.md",
                "tools": [
                        "get_conditions_to_evaluate",
                        "get_document_ocr",
                        "load_guideline_sections",
                        "store_property_evaluations"
                ],
                "substeps": [
                        {
                                "id": "5.1",
                                "name": "Load property conditions + candidate documents",
                                "tools": [
                                        "get_conditions_to_evaluate"
                                ]
                        },
                        {
                                "id": "5.2",
                                "name": "Load property/appraisal/title/insurance guideline sections (if needed)",
                                "tools": [
                                        "load_guideline_sections"
                                ]
                        },
                        {
                                "id": "5.3",
                                "name": "Store property evaluations",
                                "tools": [
                                        "store_property_evaluations"
                                ]
                        },
                        {
                                "id": "5.4",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        },
        "STEP_06": {
                "name": "Misc & Other Condition Evaluation",
                "description": "Deep fulfillment evaluation for miscellaneous/other-category conditions against their candidate documents.",
                "plan_file": "step_06_misc.md",
                "tools": [
                        "get_conditions_to_evaluate",
                        "get_document_ocr",
                        "load_guideline_sections",
                        "store_other_evaluations"
                ],
                "substeps": [
                        {
                                "id": "6.1",
                                "name": "Load misc/other conditions + candidate documents",
                                "tools": [
                                        "get_conditions_to_evaluate"
                                ]
                        },
                        {
                                "id": "6.2",
                                "name": "Load guideline sections (if needed)",
                                "tools": [
                                        "load_guideline_sections"
                                ]
                        },
                        {
                                "id": "6.3",
                                "name": "Store misc/other evaluations",
                                "tools": [
                                        "store_other_evaluations"
                                ]
                        },
                        {
                                "id": "6.4",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        },
        "STEP_07": {
                "name": "Aggregation & Human-in-the-Loop Packaging",
                "description": "Merge all per-condition evaluations, normalize verdicts, derive overall status, flag low-confidence/ambiguous items for human review, compute stats, and assemble the final output.",
                "plan_file": "step_07_aggregation.md",
                "tools": [
                        "merge_evaluations",
                        "generate_final_output"
                ],
                "substeps": [
                        {
                                "id": "7.1",
                                "name": "Merge & normalize all evaluations",
                                "tools": [
                                        "merge_evaluations"
                                ]
                        },
                        {
                                "id": "7.2",
                                "name": "Generate final output",
                                "tools": [
                                        "generate_final_output"
                                ]
                        },
                        {
                                "id": "7.3",
                                "name": "Save step report",
                                "tools": [
                                        "save_step_report"
                                ]
                        }
                ]
        }
}


STEP_ORDER: list[str] = [
        "STEP_00",
        "STEP_01",
        "STEP_02",
        "STEP_03",
        "STEP_04",
        "STEP_05",
        "STEP_06",
        "STEP_07"
]


GENERAL_TOOL_NAMES: list[str] = [
        "write_todo",
        "get_workflow_status",
        "save_step_report"
]


_DEFAULT_DEV_MODE: dict[str, Any] = {
        "enabled": False,
        "skip_steps": [],
        "cutoff_step": None,
        "run_only_substeps": []
}



def get_dev_mode(input_state: dict | None = None) -> dict[str, Any]:
    """Resolve dev mode config. Priority: input_state > env vars > config defaults."""
    mode = dict(_DEFAULT_DEV_MODE)

    if os.environ.get("DEV_MODE_ENABLED", "").lower() in ("1", "true", "yes"):
        mode["enabled"] = True
    if os.environ.get("DEV_MODE_SKIP_STEPS"):
        mode["skip_steps"] = os.environ["DEV_MODE_SKIP_STEPS"].split(",")
    if os.environ.get("DEV_MODE_CUTOFF_STEP"):
        mode["cutoff_step"] = os.environ["DEV_MODE_CUTOFF_STEP"]

    if input_state:
        state_dev = input_state.get("dev_mode") or {}
        mode.update(state_dev)

    return mode


def is_step_skipped(step_id: str, input_state: dict | None = None) -> bool:
    """Return True if this step should be skipped in dev mode."""
    dev = get_dev_mode(input_state)
    if not dev.get("enabled"):
        return False
    if step_id in (dev.get("skip_steps") or []):
        return True
    cutoff = dev.get("cutoff_step")
    if cutoff and STEP_ORDER.index(step_id) > STEP_ORDER.index(cutoff):
        return True
    return False


def get_step_tools(step_id: str) -> list[str]:
    """Return the tool names registered for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("tools", [])


def get_step_plan_file(step_id: str) -> str | None:
    """Return the plan markdown filename for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("plan_file")


def get_current_step(state: dict) -> str | None:
    """Extract the current step from agent state."""
    return state.get("current_step")
