"""
config/generate.py — Generates ../registry.py from workflow_config.json.

Run from anywhere:
    python config/generate.py

The registry encodes step -> tool / plan mappings, step ordering, the list of
always-available general tools, and dev-mode helpers. It is consumed by
step_loader.py to scope tools and plans per step.
"""

from __future__ import annotations

import json
from pathlib import Path

_CONFIG_DIR = Path(__file__).parent
_ROOT = _CONFIG_DIR.parent
_CONFIG_PATH = _CONFIG_DIR / "workflow_config.json"
_REGISTRY_PATH = _ROOT / "registry.py"


def _py(obj) -> str:
    """Render a Python literal with stable, readable formatting."""
    return json.dumps(obj, indent=8).replace("true", "True").replace("false", "False").replace("null", "None")


def generate() -> str:
    config = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
    steps = config["steps"]

    step_config: dict[str, dict] = {}
    for step in steps:
        step_config[step["id"]] = {
            "name": step["name"],
            "description": step["description"],
            "plan_file": step["plan_file"],
            "tools": step["tools"],
            "substeps": step.get("substeps", []),
        }

    step_order = [s["id"] for s in steps]
    general_tools = config.get("general_tools", [])
    dev_mode = config.get("dev_mode", {"enabled": False, "skip_steps": [], "cutoff_step": None, "run_only_substeps": []})

    blocks: list[str] = []
    blocks.append('"""')
    blocks.append("registry.py — AUTO-GENERATED by config/generate.py")
    blocks.append("DO NOT EDIT MANUALLY. Edit config/workflow_config.json and re-run generate.py.")
    blocks.append('"""')
    blocks.append("")
    blocks.append("from __future__ import annotations")
    blocks.append("")
    blocks.append("import os")
    blocks.append("from typing import Any")
    blocks.append("")
    blocks.append("")
    blocks.append(f"STEP_CONFIG: dict[str, dict[str, Any]] = {_py(step_config)}")
    blocks.append("")
    blocks.append("")
    blocks.append(f"STEP_ORDER: list[str] = {_py(step_order)}")
    blocks.append("")
    blocks.append("")
    blocks.append(f"GENERAL_TOOL_NAMES: list[str] = {_py(general_tools)}")
    blocks.append("")
    blocks.append("")
    blocks.append(f"_DEFAULT_DEV_MODE: dict[str, Any] = {_py(dev_mode)}")
    blocks.append("")
    blocks.append("")
    blocks.append(_STATIC_HELPERS)

    out = "\n".join(blocks)
    _REGISTRY_PATH.write_text(out, encoding="utf-8")
    return out


_STATIC_HELPERS = '''
def get_dev_mode(input_state: dict | None = None) -> dict[str, Any]:
    """Resolve dev mode config. Priority: input_state > env vars > config defaults."""
    mode = dict(_DEFAULT_DEV_MODE)

    if os.environ.get("DEV_MODE_ENABLED", "").lower() in ("1", "true", "yes"):
        mode["enabled"] = True
    if os.environ.get("DEV_MODE_SKIP_STEPS"):
        mode["skip_steps"] = os.environ["DEV_MODE_SKIP_STEPS"].split(",")
    if os.environ.get("DEV_MODE_CUTOFF_STEP"):
        mode["cutoff_step"] = os.environ["DEV_MODE_CUTOFF_STEP"]

    if input_state:
        state_dev = input_state.get("dev_mode") or {}
        mode.update(state_dev)

    return mode


def is_step_skipped(step_id: str, input_state: dict | None = None) -> bool:
    """Return True if this step should be skipped in dev mode."""
    dev = get_dev_mode(input_state)
    if not dev.get("enabled"):
        return False
    if step_id in (dev.get("skip_steps") or []):
        return True
    cutoff = dev.get("cutoff_step")
    if cutoff and STEP_ORDER.index(step_id) > STEP_ORDER.index(cutoff):
        return True
    return False


def get_step_tools(step_id: str) -> list[str]:
    """Return the tool names registered for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("tools", [])


def get_step_plan_file(step_id: str) -> str | None:
    """Return the plan markdown filename for a given step."""
    return STEP_CONFIG.get(step_id, {}).get("plan_file")


def get_current_step(state: dict) -> str | None:
    """Extract the current step from agent state."""
    return state.get("current_step")
'''


if __name__ == "__main__":
    generate()
    print(f"Wrote {_REGISTRY_PATH}")
